global:
  scrape_interval: 3s
  external_labels:
    monitor: 'resilience4j-monitor'
scrape_configs:
  - job_name: 'demo-prometheus-client'
    scrape_interval: 2s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8012']
  - job_name: 'ms-loan'
    scrape_interval: 2s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']