version: '2'
services:
  flink-master:
    image: bde2020/flink-master:1.14.5-hadoop3.2
    hostname: flink-master
    container_name: flink-master
    networks:
      - net
    ports:
      - "8080:8080"
      - "8081:8081"

  flink-worker:
    image: bde2020/flink-worker:1.14.5-hadoop3.2
    hostname: flink-worker
    container_name: flink-worker
    networks:
      - net
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
    depends_on:
      - flink-master

networks:
  net: