server:
  port: 8112

logging:
  level:
    ROOT: INFO
    com.company: INFO

management:
  endpoints:
    web:
      exposure:
        include: [ "env", "health", "info" ]

spring:
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8083"
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8083"
        specific:
          avro:
            reader: "true"

avro:
  topic:
    name: "operation"