version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8085:80"  # Expose NGINX on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX configuration
