version: '3.6'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./job:/etc/prometheus
      - data:/prometheus
    networks:
      - net
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - data:/var/lib/grafana
    networks:
      - net
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  data: { }

networks:
  net: